version: '2.4'

services:

  voip:
    image: ghcr.io/izer-xyz/3cx:latest
    restart: unless-stopped
    tty: true 
    #environment: # these variables are optional and used by the auto restore feature (https://github.com/izer-xyz/3cx-docker/issues/3)
      #- CX_BACKUP_FILE=/mnt/voip/backups/3CXScheduledBackup.zip
      #- CX_PUBLIC_IP=X.X.X.X
      #- CX_INTERNAL_FQDN=voip.example.com
    tmpfs:
      - /tmp/
      - /run/
      - /run/lock
    volumes:
      - voip:/mnt/voip
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "5015:5015"
      - "5060:5060"
      - "5060:5060/udp"
      - "5090:5090"
      - "5090:5090/udp"

volumes:
  voip:
